// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.21.6
// source: recognition_report.proto

package recognition_report

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RecognitionReportRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ReportTime   *timestamppb.Timestamp `protobuf:"bytes,1,opt,name=reportTime,proto3" json:"reportTime,omitempty"`
	ReporterUID  string                 `protobuf:"bytes,2,opt,name=reporterUID,proto3" json:"reporterUID,omitempty"`
	Lat          float32                `protobuf:"fixed32,3,opt,name=lat,proto3" json:"lat,omitempty"`
	Lon          float32                `protobuf:"fixed32,4,opt,name=lon,proto3" json:"lon,omitempty"`
	Speed        float32                `protobuf:"fixed32,5,opt,name=speed,proto3" json:"speed,omitempty"`
	Heading      float32                `protobuf:"fixed32,6,opt,name=heading,proto3" json:"heading,omitempty"`
	PlateNumbers string                 `protobuf:"bytes,7,opt,name=plateNumbers,proto3" json:"plateNumbers,omitempty"`
}

func (x *RecognitionReportRequest) Reset() {
	*x = RecognitionReportRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_recognition_report_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RecognitionReportRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RecognitionReportRequest) ProtoMessage() {}

func (x *RecognitionReportRequest) ProtoReflect() protoreflect.Message {
	mi := &file_recognition_report_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RecognitionReportRequest.ProtoReflect.Descriptor instead.
func (*RecognitionReportRequest) Descriptor() ([]byte, []int) {
	return file_recognition_report_proto_rawDescGZIP(), []int{0}
}

func (x *RecognitionReportRequest) GetReportTime() *timestamppb.Timestamp {
	if x != nil {
		return x.ReportTime
	}
	return nil
}

func (x *RecognitionReportRequest) GetReporterUID() string {
	if x != nil {
		return x.ReporterUID
	}
	return ""
}

func (x *RecognitionReportRequest) GetLat() float32 {
	if x != nil {
		return x.Lat
	}
	return 0
}

func (x *RecognitionReportRequest) GetLon() float32 {
	if x != nil {
		return x.Lon
	}
	return 0
}

func (x *RecognitionReportRequest) GetSpeed() float32 {
	if x != nil {
		return x.Speed
	}
	return 0
}

func (x *RecognitionReportRequest) GetHeading() float32 {
	if x != nil {
		return x.Heading
	}
	return 0
}

func (x *RecognitionReportRequest) GetPlateNumbers() string {
	if x != nil {
		return x.PlateNumbers
	}
	return ""
}

type RecognitionReportResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ResponseStatus int32 `protobuf:"varint,1,opt,name=responseStatus,proto3" json:"responseStatus,omitempty"`
}

func (x *RecognitionReportResponse) Reset() {
	*x = RecognitionReportResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_recognition_report_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RecognitionReportResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RecognitionReportResponse) ProtoMessage() {}

func (x *RecognitionReportResponse) ProtoReflect() protoreflect.Message {
	mi := &file_recognition_report_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RecognitionReportResponse.ProtoReflect.Descriptor instead.
func (*RecognitionReportResponse) Descriptor() ([]byte, []int) {
	return file_recognition_report_proto_rawDescGZIP(), []int{1}
}

func (x *RecognitionReportResponse) GetResponseStatus() int32 {
	if x != nil {
		return x.ResponseStatus
	}
	return 0
}

var File_recognition_report_proto protoreflect.FileDescriptor

var file_recognition_report_proto_rawDesc = []byte{
	0x0a, 0x18, 0x72, 0x65, 0x63, 0x6f, 0x67, 0x6e, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x5f, 0x72, 0x65,
	0x70, 0x6f, 0x72, 0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x1f, 0x67, 0x6f, 0x6f, 0x67,
	0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x74, 0x69, 0x6d, 0x65,
	0x73, 0x74, 0x61, 0x6d, 0x70, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0xf0, 0x01, 0x0a, 0x18,
	0x52, 0x65, 0x63, 0x6f, 0x67, 0x6e, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x70, 0x6f, 0x72,
	0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x3a, 0x0a, 0x0a, 0x72, 0x65, 0x70, 0x6f,
	0x72, 0x74, 0x54, 0x69, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x67,
	0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x54,
	0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x52, 0x0a, 0x72, 0x65, 0x70, 0x6f, 0x72, 0x74,
	0x54, 0x69, 0x6d, 0x65, 0x12, 0x20, 0x0a, 0x0b, 0x72, 0x65, 0x70, 0x6f, 0x72, 0x74, 0x65, 0x72,
	0x55, 0x49, 0x44, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x72, 0x65, 0x70, 0x6f, 0x72,
	0x74, 0x65, 0x72, 0x55, 0x49, 0x44, 0x12, 0x10, 0x0a, 0x03, 0x6c, 0x61, 0x74, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x02, 0x52, 0x03, 0x6c, 0x61, 0x74, 0x12, 0x10, 0x0a, 0x03, 0x6c, 0x6f, 0x6e, 0x18,
	0x04, 0x20, 0x01, 0x28, 0x02, 0x52, 0x03, 0x6c, 0x6f, 0x6e, 0x12, 0x14, 0x0a, 0x05, 0x73, 0x70,
	0x65, 0x65, 0x64, 0x18, 0x05, 0x20, 0x01, 0x28, 0x02, 0x52, 0x05, 0x73, 0x70, 0x65, 0x65, 0x64,
	0x12, 0x18, 0x0a, 0x07, 0x68, 0x65, 0x61, 0x64, 0x69, 0x6e, 0x67, 0x18, 0x06, 0x20, 0x01, 0x28,
	0x02, 0x52, 0x07, 0x68, 0x65, 0x61, 0x64, 0x69, 0x6e, 0x67, 0x12, 0x22, 0x0a, 0x0c, 0x70, 0x6c,
	0x61, 0x74, 0x65, 0x4e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x73, 0x18, 0x07, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x0c, 0x70, 0x6c, 0x61, 0x74, 0x65, 0x4e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x73, 0x22, 0x43,
	0x0a, 0x19, 0x52, 0x65, 0x63, 0x6f, 0x67, 0x6e, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x70,
	0x6f, 0x72, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x26, 0x0a, 0x0e, 0x72,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x05, 0x52, 0x0e, 0x72, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x53, 0x74, 0x61,
	0x74, 0x75, 0x73, 0x32, 0x54, 0x0a, 0x11, 0x52, 0x65, 0x63, 0x6f, 0x67, 0x6e, 0x69, 0x74, 0x69,
	0x6f, 0x6e, 0x52, 0x65, 0x70, 0x6f, 0x72, 0x74, 0x12, 0x3f, 0x0a, 0x06, 0x43, 0x72, 0x65, 0x61,
	0x74, 0x65, 0x12, 0x19, 0x2e, 0x52, 0x65, 0x63, 0x6f, 0x67, 0x6e, 0x69, 0x74, 0x69, 0x6f, 0x6e,
	0x52, 0x65, 0x70, 0x6f, 0x72, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1a, 0x2e,
	0x52, 0x65, 0x63, 0x6f, 0x67, 0x6e, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x70, 0x6f, 0x72,
	0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x42, 0x1d, 0x5a, 0x1b, 0x70, 0x6b, 0x67,
	0x2f, 0x67, 0x72, 0x70, 0x63, 0x2f, 0x72, 0x65, 0x63, 0x6f, 0x67, 0x6e, 0x69, 0x74, 0x69, 0x6f,
	0x6e, 0x5f, 0x72, 0x65, 0x70, 0x6f, 0x72, 0x74, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_recognition_report_proto_rawDescOnce sync.Once
	file_recognition_report_proto_rawDescData = file_recognition_report_proto_rawDesc
)

func file_recognition_report_proto_rawDescGZIP() []byte {
	file_recognition_report_proto_rawDescOnce.Do(func() {
		file_recognition_report_proto_rawDescData = protoimpl.X.CompressGZIP(file_recognition_report_proto_rawDescData)
	})
	return file_recognition_report_proto_rawDescData
}

var file_recognition_report_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_recognition_report_proto_goTypes = []interface{}{
	(*RecognitionReportRequest)(nil),  // 0: RecognitionReportRequest
	(*RecognitionReportResponse)(nil), // 1: RecognitionReportResponse
	(*timestamppb.Timestamp)(nil),     // 2: google.protobuf.Timestamp
}
var file_recognition_report_proto_depIdxs = []int32{
	2, // 0: RecognitionReportRequest.reportTime:type_name -> google.protobuf.Timestamp
	0, // 1: RecognitionReport.Create:input_type -> RecognitionReportRequest
	1, // 2: RecognitionReport.Create:output_type -> RecognitionReportResponse
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_recognition_report_proto_init() }
func file_recognition_report_proto_init() {
	if File_recognition_report_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_recognition_report_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RecognitionReportRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_recognition_report_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RecognitionReportResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_recognition_report_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_recognition_report_proto_goTypes,
		DependencyIndexes: file_recognition_report_proto_depIdxs,
		MessageInfos:      file_recognition_report_proto_msgTypes,
	}.Build()
	File_recognition_report_proto = out.File
	file_recognition_report_proto_rawDesc = nil
	file_recognition_report_proto_goTypes = nil
	file_recognition_report_proto_depIdxs = nil
}
